project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
      - text: Take-home Exercise
        menu: 
          - href: Take-home Exercise/Take-home Exercise 1/Take-home Exercise 1.qmd
            text: Take-home Exercise 1
          - href: Take-home Exercise/Take-home Exercise 2/Take-home Exercise 2.qmd
            text: Take-home Exercise 2
      - text: In-class Exercise
        menu: 
          - href: In-class Exercise/In-class Ex3/In-class Ex3.qmd
            text: In-class Ex3
          - href: In-class Exercise/In-class Ex4/In-class Ex4.qmd
            text: In-class Ex4
          - href: In-class Exercise/In-class Ex5/In-class Ex5.qmd
            text: In-class Ex5
    right: 
       - href: index.qmd
         text: Home
       - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

